### ISSUE TITLE
OHCLV data straight outta Robinhood

### ISSUE THREAD

**Issue by doctorcolossus** [sshh12/Tradinhood#7]
Hey Shrivu. It is cool that your library provides an interface to OHCLV data from google and cryptocompare, but I would also like to be able to get it straight from Robinhood. I know it doesn't go back very far, but still - it's good to have access to price data straight from the exchange you're trading on. If you would be interested in implementing this, you could reference [how wang-ye does it in robinhood-crypto](https://github.com/wang-ye/robinhood-crypto/blob/bc6daecd6127625e7d0b3544d461219e0c54fcab/robinhood_crypto_api/robinhood_crypto_api.py#L304).

**Comment by sshh12** [comment]
Voila https://github.com/sshh12/Tradinhood/pull/8:
```python
dataset = Dataset.from_robinhood(rbh['BTC'], resolution='5m')
dataset |= Dataset.from_robinhood(rbh['AMD'], resolution='5m')
```
Any other suggestions/additions before I make a release for this?

**Comment by alexonab** [comment]
Any reason for only 5m or 1d intervals? Does Robinhood support 1m or tick data?

**Comment by doctorcolossus** [comment]
Good catch. I forget where I found this or if I just used trial & error, but the minimum interval='15second' with span='hour'. I would love to have support for that. Only certain combinations of intervals & span work. I remember noting them down somewhere, so I'll report back if I can find that...

**Comment by doctorcolossus** [comment]
According to my notes, the following combinations worked:
```
interval='15second', span='hour'
interval='5minute',  span='day'
interval='day',      span='year'
interval='week',     span='5year'
```

**Comment by sshh12** [comment]
Updated #8 to accept `[15s, 5m, 1d, 1w]`.
